export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'

export const GET_TOP_PRODUCTS_REQUEST = 'GET_TOP_PRODUCTS_REQUEST'
export const GET_TOP_PRODUCTS_SUCCESS = 'GET_TOP_PRODUCTS_SUCCESS'
export const GET_TOP_PRODUCTS_FAIL = 'GET_TOP_PRODUCTS_FAIL'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST'
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL'


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'
export const GET_USER_PROFILE_RESET = 'GET_USER_PROFILE_RESET'

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'



export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'



export const GET_USERS_BY_ADMIN_REQUEST = 'GET_USERS_BY_ADMIN_REQUEST'
export const GET_USERS_BY_ADMIN_SUCCESS = 'GET_USERS_BY_ADMIN_SUCCESS'
export const GET_USERS_BY_ADMIN_FAIL = 'GET_USERS_BY_ADMIN_FAIL'

export const DELETE_USER_BY_ADMIN_REQUEST = 'DELETE_USER_BY_ADMIN_REQUEST'
export const DELETE_USER_BY_ADMIN_SUCCESS = 'DELETE_USER_BY_ADMIN_SUCCESS'
export const DELETE_USER_BY_ADMIN_FAIL = 'DELETE_USER_BY_ADMIN_FAIL'

export const DELETE_PRODUCT_BY_ADMIN_REQUEST = 'DELETE_PRODUCT_BY_ADMIN_REQUEST'
export const DELETE_PRODUCT_BY_ADMIN_SUCCESS = 'DELETE_PRODUCT_BY_ADMIN_SUCCESS'
export const DELETE_PRODUCT_BY_ADMIN_FAIL = 'DELETE_PRODUCT_BY_ADMIN_FAIL'

export const ADD_PRODUCT_BY_ADMIN_REQUEST = 'ADD_PRODUCT_BY_ADMIN_REQUEST'
export const ADD_PRODUCT_BY_ADMIN_SUCCESS = 'ADD_PRODUCT_BY_ADMIN_SUCCESS'
export const ADD_PRODUCT_BY_ADMIN_FAIL = 'ADD_PRODUCT_BY_ADMIN_FAIL'

export const UPDATE_PRODUCT_BY_ADMIN_REQUEST = 'UPDATE_PRODUCT_BY_ADMIN_REQUEST'
export const UPDATE_PRODUCT_BY_ADMIN_SUCCESS = 'UPDATE_PRODUCT_BY_ADMIN_SUCCESS'
export const UPDATE_PRODUCT_BY_ADMIN_FAIL = 'UPDATE_PRODUCT_BY_ADMIN_FAIL'

export const GET_MY_ORDERS_REQUEST = 'GET_MY_ORDERS_REQUEST'
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS'
export const GET_MY_ORDERS_FAIL = 'GET_MY_ORDERS_FAIL'
export const GET_MY_ORDERS_RESET = 'GET_MY_ORDERS_RESET'

export const GET_MY_ORDERS_DETAILS_REQUEST = 'GET_MY_ORDERS_DETAILS_REQUEST'
export const GET_MY_ORDERS_DETAILS_SUCCESS = 'GET_MY_ORDERS_DETAILS_SUCCESS'
export const GET_MY_ORDERS_DETAILS_FAIL = 'GET_MY_ORDERS_DETAILS_FAIL'
export const GET_MY_ORDERS_DETAILS_RESET = 'GET_MY_ORDERS_DETAILS_RESET'

export const GET_ORDERS_BY_ADMIN_REQUEST = 'GET_ORDERS_BY_ADMIN_REQUEST'
export const GET_ORDERS_BY_ADMIN_SUCCESS = 'GET_ORDERS_BY_ADMIN_SUCCESS'
export const GET_ORDERS_BY_ADMIN_FAIL = 'GET_ORDERS_BY_ADMIN_FAIL'

export const DELIVER_ORDER_BY_ADMIN_REQUEST = 'DELIVER_ORDER_BY_ADMIN_REQUEST'
export const DELIVER_ORDER_BY_ADMIN_SUCCESS = 'DELIVER_ORDER_BY_ADMIN_SUCCESS'
export const DELIVER_ORDER_BY_ADMIN_FAIL = 'DELIVER_ORDER_BY_ADMIN_FAIL'
